apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
        access: proxy
        isDefault: false
        orgId: 1
        version: 1
        editable: false
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
            filterBySpanID: false
          lokiSearch:
            datasourceUid: loki
