[control_plane]
k8s-control-plane ansible_host=orb ansible_user=marcomontilla@k8s-control-plane

[workers]
k8s-worker-node1 ansible_host=orb ansible_user=marcomontilla@k8s-worker-node1
k8s-worker-node2 ansible_host=orb ansible_user=marcomontilla@k8s-worker-node2

[k8s_cluster:children]
control_plane
workers
